"""
read_intan_rhd2000.py

Version 2.0, translated from MATLAB (20 October 2016)

Reads Intan Technologies RHD2000 data files generated by the evaluation board
GUI or Intan Recording Controller. Returns a dictionary with all parsed data.

Example usage:
    from read_intan_rhd2000 import read_rhd2000_file
    data = read_rhd2000_file('recording.rhd')
    import matplotlib.pyplot as plt
    plt.plot(data['t_amplifier'], data['amplifier_data'][0])
    plt.show()
"""

import struct
import os
import time
import numpy as np
from tkinter import Tk, filedialog


# ---------------------------------------------------------------------------
# Helper: read Qt-style QString
# ---------------------------------------------------------------------------

def read_qstring(fid):
    """
    Read a Qt-style QString from an open binary file.
    The first uint32 gives the byte length of the string.
    0xFFFFFFFF means the string is null/empty.
    """
    length_bytes = fid.read(4)
    if len(length_bytes) < 4:
        return ''
    length = struct.unpack('<I', length_bytes)[0]
    if length == 0xFFFFFFFF:
        return ''
    # Length is in bytes; each Unicode character is 2 bytes (UTF-16LE)
    num_chars = length // 2
    chars = []
    for _ in range(num_chars):
        word = struct.unpack('<H', fid.read(2))[0]
        chars.append(chr(word))
    return ''.join(chars)


# ---------------------------------------------------------------------------
# Helper: notch filter
# ---------------------------------------------------------------------------

def notch_filter(signal, f_sample, f_notch, bandwidth):
    """
    Implements a notch filter (e.g. 50 or 60 Hz) on a 1-D array.

    Parameters
    ----------
    signal    : 1-D numpy array
    f_sample  : sample rate (Hz)
    f_notch   : notch frequency (Hz)
    bandwidth : notch 3-dB bandwidth (Hz); 10 Hz is recommended

    Returns
    -------
    out : filtered 1-D numpy array
    """
    tstep = 1.0 / f_sample
    Fc = f_notch * tstep
    L = len(signal)

    d = np.exp(-2.0 * np.pi * (bandwidth / 2.0) * tstep)
    b = (1.0 + d * d) * np.cos(2.0 * np.pi * Fc)
    a0 = 1.0
    a1 = -b
    a2 = d * d
    a = (1.0 + d * d) / 2.0
    b0 = 1.0
    b1 = -2.0 * np.cos(2.0 * np.pi * Fc)
    b2 = 1.0

    out = np.zeros(L)
    out[0] = signal[0]
    if L > 1:
        out[1] = signal[1]

    for i in range(2, L):
        out[i] = (
            a * b2 * signal[i - 2]
            + a * b1 * signal[i - 1]
            + a * b0 * signal[i]
            - a2 * out[i - 2]
            - a1 * out[i - 1]
        ) / a0

    return out


# ---------------------------------------------------------------------------
# Helper: read a typed scalar from the file
# ---------------------------------------------------------------------------

_FMT = {
    'uint32': ('<I', 4),
    'int16':  ('<h', 2),
    'uint16': ('<H', 2),
    'int32':  ('<i', 4),
    'single': ('<f', 4),
}

def fread_scalar(fid, dtype):
    fmt, size = _FMT[dtype]
    return struct.unpack(fmt, fid.read(size))[0]


# ---------------------------------------------------------------------------
# Main reader
# ---------------------------------------------------------------------------

def read_rhd2000_file(filename=None):
    """
    Read an Intan RHD2000 data file.

    Parameters
    ----------
    filename : str or None
        Path to a .rhd file. If None, a file-chooser dialog is opened.

    Returns
    -------
    result : dict
        Dictionary containing all parsed header information and data arrays.
        Keys mirror the MATLAB workspace variables produced by the original
        script, e.g. 'amplifier_data', 't_amplifier', 'frequency_parameters',
        'amplifier_channels', etc.
    """

    # --- File selection ---------------------------------------------------
    if filename is None:
        root = Tk()
        root.withdraw()
        filename = filedialog.askopenfilename(
            title='Select an RHD2000 Data File',
            filetypes=[('RHD2000 files', '*.rhd'), ('All files', '*.*')]
        )
        root.destroy()
        if not filename:
            print('No file selected.')
            return {}

    t_start = time.time()
    filesize = os.path.getsize(filename)

    with open(filename, 'rb') as fid:

        # --- Magic number -------------------------------------------------
        magic_number = fread_scalar(fid, 'uint32')
        if magic_number != 0xC6912702:
            raise ValueError('Unrecognized file type (magic number mismatch).')

        # --- Version ------------------------------------------------------
        main_ver = fread_scalar(fid, 'int16')
        sec_ver  = fread_scalar(fid, 'int16')
        print(f'\nReading Intan Technologies RHD2000 Data File, Version {main_ver}.{sec_ver}\n')

        num_samples_per_data_block = 60 if main_ver == 1 else 128

        # --- Sampling / filter settings -----------------------------------
        sample_rate                  = fread_scalar(fid, 'single')
        dsp_enabled                  = fread_scalar(fid, 'int16')
        actual_dsp_cutoff_frequency  = fread_scalar(fid, 'single')
        actual_lower_bandwidth       = fread_scalar(fid, 'single')
        actual_upper_bandwidth       = fread_scalar(fid, 'single')
        desired_dsp_cutoff_frequency = fread_scalar(fid, 'single')
        desired_lower_bandwidth      = fread_scalar(fid, 'single')
        desired_upper_bandwidth      = fread_scalar(fid, 'single')

        notch_filter_mode = fread_scalar(fid, 'int16')
        notch_filter_frequency = {0: 0, 1: 50, 2: 60}.get(notch_filter_mode, 0)

        desired_impedance_test_frequency = fread_scalar(fid, 'single')
        actual_impedance_test_frequency  = fread_scalar(fid, 'single')

        # --- Notes --------------------------------------------------------
        notes = {
            'note1': read_qstring(fid),
            'note2': read_qstring(fid),
            'note3': read_qstring(fid),
        }

        # --- Optional fields based on version -----------------------------
        num_temp_sensor_channels = 0
        if (main_ver == 1 and sec_ver >= 1) or main_ver > 1:
            num_temp_sensor_channels = fread_scalar(fid, 'int16')

        eval_board_mode = 0
        if (main_ver == 1 and sec_ver >= 3) or main_ver > 1:
            eval_board_mode = fread_scalar(fid, 'int16')

        reference_channel = ''
        if main_ver > 1:
            reference_channel = read_qstring(fid)

        # --- Frequency parameters dict ------------------------------------
        frequency_parameters = {
            'amplifier_sample_rate':           sample_rate,
            'aux_input_sample_rate':           sample_rate / 4,
            'supply_voltage_sample_rate':      sample_rate / num_samples_per_data_block,
            'board_adc_sample_rate':           sample_rate,
            'board_dig_in_sample_rate':        sample_rate,
            'desired_dsp_cutoff_frequency':    desired_dsp_cutoff_frequency,
            'actual_dsp_cutoff_frequency':     actual_dsp_cutoff_frequency,
            'dsp_enabled':                     dsp_enabled,
            'desired_lower_bandwidth':         desired_lower_bandwidth,
            'actual_lower_bandwidth':          actual_lower_bandwidth,
            'desired_upper_bandwidth':         desired_upper_bandwidth,
            'actual_upper_bandwidth':          actual_upper_bandwidth,
            'notch_filter_frequency':          notch_filter_frequency,
            'desired_impedance_test_frequency': desired_impedance_test_frequency,
            'actual_impedance_test_frequency':  actual_impedance_test_frequency,
        }

        # --- Channel containers -------------------------------------------
        amplifier_channels      = []
        aux_input_channels      = []
        supply_voltage_channels = []
        board_adc_channels      = []
        board_dig_in_channels   = []
        board_dig_out_channels  = []
        spike_triggers          = []

        # --- Read signal groups from header -------------------------------
        number_of_signal_groups = fread_scalar(fid, 'int16')

        for _ in range(number_of_signal_groups):
            signal_group_name        = read_qstring(fid)
            signal_group_prefix      = read_qstring(fid)
            signal_group_enabled     = fread_scalar(fid, 'int16')
            signal_group_num_channels     = fread_scalar(fid, 'int16')
            signal_group_num_amp_channels = fread_scalar(fid, 'int16')  # noqa (read but unused)

            if signal_group_num_channels > 0 and signal_group_enabled > 0:
                for _ in range(signal_group_num_channels):
                    native_channel_name  = read_qstring(fid)
                    custom_channel_name  = read_qstring(fid)
                    native_order         = fread_scalar(fid, 'int16')
                    custom_order         = fread_scalar(fid, 'int16')
                    signal_type          = fread_scalar(fid, 'int16')
                    channel_enabled      = fread_scalar(fid, 'int16')
                    chip_channel         = fread_scalar(fid, 'int16')
                    board_stream         = fread_scalar(fid, 'int16')

                    voltage_trigger_mode    = fread_scalar(fid, 'int16')
                    voltage_threshold       = fread_scalar(fid, 'int16')
                    digital_trigger_channel = fread_scalar(fid, 'int16')
                    digital_edge_polarity   = fread_scalar(fid, 'int16')

                    electrode_impedance_magnitude = fread_scalar(fid, 'single')
                    electrode_impedance_phase     = fread_scalar(fid, 'single')

                    if channel_enabled:
                        ch = {
                            'native_channel_name':           native_channel_name,
                            'custom_channel_name':           custom_channel_name,
                            'native_order':                  native_order,
                            'custom_order':                  custom_order,
                            'board_stream':                  board_stream,
                            'chip_channel':                  chip_channel,
                            'port_name':                     signal_group_name,
                            'port_prefix':                   signal_group_prefix,
                            'port_number':                   _,
                            'electrode_impedance_magnitude': electrode_impedance_magnitude,
                            'electrode_impedance_phase':     electrode_impedance_phase,
                        }
                        trig = {
                            'voltage_trigger_mode':    voltage_trigger_mode,
                            'voltage_threshold':       voltage_threshold,
                            'digital_trigger_channel': digital_trigger_channel,
                            'digital_edge_polarity':   digital_edge_polarity,
                        }

                        if signal_type == 0:
                            amplifier_channels.append(ch)
                            spike_triggers.append(trig)
                        elif signal_type == 1:
                            aux_input_channels.append(ch)
                        elif signal_type == 2:
                            supply_voltage_channels.append(ch)
                        elif signal_type == 3:
                            board_adc_channels.append(ch)
                        elif signal_type == 4:
                            board_dig_in_channels.append(ch)
                        elif signal_type == 5:
                            board_dig_out_channels.append(ch)
                        else:
                            raise ValueError(f'Unknown channel type: {signal_type}')

        # --- Channel counts -----------------------------------------------
        num_amplifier_channels      = len(amplifier_channels)
        num_aux_input_channels      = len(aux_input_channels)
        num_supply_voltage_channels = len(supply_voltage_channels)
        num_board_adc_channels      = len(board_adc_channels)
        num_board_dig_in_channels   = len(board_dig_in_channels)
        num_board_dig_out_channels  = len(board_dig_out_channels)

        def plural(n): return '' if n == 1 else 's'

        print(f'Found {num_amplifier_channels} amplifier channel{plural(num_amplifier_channels)}.')
        print(f'Found {num_aux_input_channels} auxiliary input channel{plural(num_aux_input_channels)}.')
        print(f'Found {num_supply_voltage_channels} supply voltage channel{plural(num_supply_voltage_channels)}.')
        print(f'Found {num_board_adc_channels} board ADC channel{plural(num_board_adc_channels)}.')
        print(f'Found {num_board_dig_in_channels} board digital input channel{plural(num_board_dig_in_channels)}.')
        print(f'Found {num_board_dig_out_channels} board digital output channel{plural(num_board_dig_out_channels)}.')
        print(f'Found {num_temp_sensor_channels} temperature sensor channel{plural(num_temp_sensor_channels)}.')
        print()

        # --- Bytes per data block -----------------------------------------
        bytes_per_block = num_samples_per_data_block * 4  # timestamps (int32)
        bytes_per_block += num_samples_per_data_block * 2 * num_amplifier_channels
        bytes_per_block += (num_samples_per_data_block // 4) * 2 * num_aux_input_channels
        bytes_per_block += 1 * 2 * num_supply_voltage_channels
        bytes_per_block += num_samples_per_data_block * 2 * num_board_adc_channels
        if num_board_dig_in_channels > 0:
            bytes_per_block += num_samples_per_data_block * 2
        if num_board_dig_out_channels > 0:
            bytes_per_block += num_samples_per_data_block * 2
        if num_temp_sensor_channels > 0:
            bytes_per_block += 1 * 2 * num_temp_sensor_channels

        # --- How much data remains? ---------------------------------------
        header_end = fid.tell()
        bytes_remaining = filesize - header_end
        data_present = bytes_remaining > 0

        num_data_blocks = bytes_remaining // bytes_per_block

        num_amplifier_samples      = num_samples_per_data_block * num_data_blocks
        num_aux_input_samples      = (num_samples_per_data_block // 4) * num_data_blocks
        num_supply_voltage_samples = 1 * num_data_blocks
        num_board_adc_samples      = num_samples_per_data_block * num_data_blocks
        num_board_dig_in_samples   = num_samples_per_data_block * num_data_blocks
        num_board_dig_out_samples  = num_samples_per_data_block * num_data_blocks

        record_time = num_amplifier_samples / sample_rate if sample_rate else 0

        if data_present:
            print(f'File contains {record_time:.3f} seconds of data.  '
                  f'Amplifiers were sampled at {sample_rate / 1000:.2f} kS/s.\n')
        else:
            print(f'Header file contains no data.  '
                  f'Amplifiers were sampled at {sample_rate / 1000:.2f} kS/s.\n')

        # --- Pre-allocate arrays ------------------------------------------
        t_amplifier         = np.zeros(num_amplifier_samples, dtype=np.int32)
        amplifier_data      = np.zeros((num_amplifier_channels, num_amplifier_samples),      dtype=np.uint16)
        aux_input_data      = np.zeros((num_aux_input_channels, num_aux_input_samples),      dtype=np.uint16)
        supply_voltage_data = np.zeros((num_supply_voltage_channels, num_supply_voltage_samples), dtype=np.uint16)
        temp_sensor_data    = np.zeros((num_temp_sensor_channels, num_supply_voltage_samples),    dtype=np.int16)
        board_adc_data      = np.zeros((num_board_adc_channels, num_board_adc_samples),      dtype=np.uint16)
        board_dig_in_raw    = np.zeros(num_board_dig_in_samples,  dtype=np.uint16)
        board_dig_out_raw   = np.zeros(num_board_dig_out_samples, dtype=np.uint16)

        # --- Read data blocks ---------------------------------------------
        if data_present:
            print('Allocating memory for data...')
            print('Reading data from file...')

            amp_idx  = 0
            aux_idx  = 0
            sv_idx   = 0
            adc_idx  = 0
            din_idx  = 0
            dout_idx = 0

            print_increment = 10
            percent_done = print_increment

            spb = num_samples_per_data_block  # shorthand

            for i in range(num_data_blocks):
                # Timestamps
                if (main_ver == 1 and sec_ver >= 2) or main_ver > 1:
                    ts = np.frombuffer(fid.read(spb * 4), dtype='<i4')
                else:
                    ts = np.frombuffer(fid.read(spb * 4), dtype='<u4').astype(np.int32)
                t_amplifier[amp_idx:amp_idx + spb] = ts

                # Amplifier channels (uint16, interleaved: [sample, channel])
                if num_amplifier_channels > 0:
                    raw = np.frombuffer(fid.read(spb * 2 * num_amplifier_channels), dtype='<u2')
                    amplifier_data[:, amp_idx:amp_idx + spb] = raw.reshape(spb, num_amplifier_channels).T

                # Aux inputs (sampled at spb/4 rate)
                aux_spb = spb // 4
                if num_aux_input_channels > 0:
                    raw = np.frombuffer(fid.read(aux_spb * 2 * num_aux_input_channels), dtype='<u2')
                    aux_input_data[:, aux_idx:aux_idx + aux_spb] = raw.reshape(aux_spb, num_aux_input_channels).T

                # Supply voltage (one sample per block)
                if num_supply_voltage_channels > 0:
                    raw = np.frombuffer(fid.read(2 * num_supply_voltage_channels), dtype='<u2')
                    supply_voltage_data[:, sv_idx] = raw

                # Temperature sensors (one sample per block)
                if num_temp_sensor_channels > 0:
                    raw = np.frombuffer(fid.read(2 * num_temp_sensor_channels), dtype='<i2')
                    temp_sensor_data[:, sv_idx] = raw

                # Board ADC
                if num_board_adc_channels > 0:
                    raw = np.frombuffer(fid.read(spb * 2 * num_board_adc_channels), dtype='<u2')
                    board_adc_data[:, adc_idx:adc_idx + spb] = raw.reshape(spb, num_board_adc_channels).T

                # Digital inputs (raw bitmask)
                if num_board_dig_in_channels > 0:
                    raw = np.frombuffer(fid.read(spb * 2), dtype='<u2')
                    board_dig_in_raw[din_idx:din_idx + spb] = raw

                # Digital outputs (raw bitmask)
                if num_board_dig_out_channels > 0:
                    raw = np.frombuffer(fid.read(spb * 2), dtype='<u2')
                    board_dig_out_raw[dout_idx:dout_idx + spb] = raw

                amp_idx  += spb
                aux_idx  += aux_spb
                sv_idx   += 1
                adc_idx  += spb
                din_idx  += spb
                dout_idx += spb

                fraction_done = 100 * (i + 1) / num_data_blocks
                if fraction_done >= percent_done:
                    print(f'{percent_done}% done...')
                    percent_done += print_increment

    # --- Post-processing (outside the 'with' block) ----------------------

    if data_present:
        print('Parsing data...')

        # Unpack digital input/output channels from bitmasks
        board_dig_in_data  = np.zeros((num_board_dig_in_channels,  num_board_dig_in_samples),  dtype=bool)
        board_dig_out_data = np.zeros((num_board_dig_out_channels, num_board_dig_out_samples), dtype=bool)

        for i, ch in enumerate(board_dig_in_channels):
            mask = 2 ** ch['native_order']
            board_dig_in_data[i, :] = (board_dig_in_raw & mask) > 0

        for i, ch in enumerate(board_dig_out_channels):
            mask = 2 ** ch['native_order']
            board_dig_out_data[i, :] = (board_dig_out_raw & mask) > 0

        # Scale voltages
        amplifier_data      = 0.195 * (amplifier_data.astype(np.float64) - 32768)  # µV
        aux_input_data      = 37.4e-6 * aux_input_data.astype(np.float64)           # V
        supply_voltage_data = 74.8e-6 * supply_voltage_data.astype(np.float64)      # V
        temp_sensor_data    = temp_sensor_data.astype(np.float64) / 100.0           # °C

        if eval_board_mode == 1:
            board_adc_data = 152.59e-6 * (board_adc_data.astype(np.float64) - 32768)   # V
        elif eval_board_mode == 13:  # Intan Recording Controller
            board_adc_data = 312.5e-6 * (board_adc_data.astype(np.float64) - 32768)    # V
        else:
            board_adc_data = 50.354e-6 * board_adc_data.astype(np.float64)             # V

        # Check for timestamp gaps
        num_gaps = int(np.sum(np.diff(t_amplifier) != 1))
        if num_gaps == 0:
            print('No missing timestamps in data.')
        else:
            print(f'Warning: {num_gaps} gaps in timestamp data found.  '
                  'Time scale will not be uniform!')

        # Scale time to seconds
        t_amplifier     = t_amplifier / sample_rate
        t_aux_input     = t_amplifier[::4]
        t_supply_voltage = t_amplifier[::num_samples_per_data_block]
        t_board_adc     = t_amplifier
        t_dig           = t_amplifier
        t_temp_sensor   = t_supply_voltage

        # Apply notch filter if it was active during recording
        if notch_filter_frequency > 0:
            print('Applying notch filter...')
            print_increment = 10
            percent_done = print_increment
            for i in range(num_amplifier_channels):
                amplifier_data[i, :] = notch_filter(
                    amplifier_data[i, :], sample_rate, notch_filter_frequency, 10
                )
                fraction_done = 100 * (i + 1) / num_amplifier_channels
                if fraction_done >= percent_done:
                    print(f'{percent_done}% done...')
                    percent_done += print_increment

    # --- Assemble result dict --------------------------------------------
    result = {
        'notes':               notes,
        'frequency_parameters': frequency_parameters,
        'reference_channel':   reference_channel,
        'amplifier_channels':  amplifier_channels,
        'spike_triggers':      spike_triggers,
        'aux_input_channels':      aux_input_channels,
        'supply_voltage_channels': supply_voltage_channels,
        'board_adc_channels':      board_adc_channels,
        'board_dig_in_channels':   board_dig_in_channels,
        'board_dig_out_channels':  board_dig_out_channels,
    }

    if data_present:
        result.update({
            'amplifier_data':      amplifier_data,
            't_amplifier':         t_amplifier,
            'aux_input_data':      aux_input_data,
            't_aux_input':         t_aux_input,
            'supply_voltage_data': supply_voltage_data,
            't_supply_voltage':    t_supply_voltage,
            'board_adc_data':      board_adc_data,
            't_board_adc':         t_board_adc,
            'board_dig_in_data':   board_dig_in_data,
            'board_dig_out_data':  board_dig_out_data,
            't_dig':               t_dig,
            'temp_sensor_data':    temp_sensor_data,
            't_temp_sensor':       t_temp_sensor,
        })

    elapsed = time.time() - t_start
    print(f'\nDone!  Elapsed time: {elapsed:.1f} seconds')
    if data_present:
        print('Extracted data are now available in the returned dictionary.')
    else:
        print('Extracted waveform information is now available in the returned dictionary.')

    return result


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == '__main__':
    data = read_rhd2000_file()
    if data:
        print('\n--- Data Structure Overview ---')
        print(f"{'Key':<25} | {'Type':<15} | {'Shape/Size'}")
        print("-" * 60)

        for key, value in data.items():
            # Handle NumPy arrays (print shape)
            if isinstance(value, np.ndarray):
                info = f"Shape: {value.shape}"

            # Handle Lists (print length)
            elif isinstance(value, list):
                info = f"Length: {len(value)}"

            # Handle Dictionaries (print number of keys)
            elif isinstance(value, dict):
                info = f"Keys: {len(value)}"

            # Handle Strings/Other
            else:
                info = str(value) if len(str(value)) < 20 else "..."

            print(f"{key:<25} | {type(value).__name__:<15} | {info}")
