#ifndef TREE_WEIGHTS_H
#define TREE_WEIGHTS_H

// Auto-generated by generate_tree_cpp.py -- do not edit by hand
// Classes: 0=NOSIGNAL, 1=DORSIFLEXION, 2=PLANTARFLEXION

#define TREE_N_FEATURES 280
#define TREE_N_CLASSES 3
#define TREE_N_TREES 1

struct TreeNode {
  int16_t feature; // -2 marks a leaf
  int16_t left;
  int16_t right;
  float threshold;
  float probs[TREE_N_CLASSES];
};

const TreeNode tree0_nodes[] = {
    {193, 1, 14, -0.443777f, {0.000000f, 0.000000f, 0.000000f}},
    {30, 2, 9, -1.360518f, {0.000000f, 0.000000f, 0.000000f}},
    {14, 3, 8, -1.338959f, {0.000000f, 0.000000f, 0.000000f}},
    {28, 4, 5, -1.601475f, {0.000000f, 0.000000f, 0.000000f}},
    {-2, -1, -1, 0.000000f, {0.215714f, 0.761429f, 0.022857f}},
    {55, 6, 7, -1.489878f, {0.000000f, 0.000000f, 0.000000f}},
    {-2, -1, -1, 0.000000f, {0.670528f, 0.168597f, 0.160875f}},
    {-2, -1, -1, 0.000000f, {0.348857f, 0.596105f, 0.055038f}},
    {-2, -1, -1, 0.000000f, {0.161959f, 0.800377f, 0.037665f}},
    {66, 10, 13, 1.411552f, {0.000000f, 0.000000f, 0.000000f}},
    {263, 11, 12, -0.359232f, {0.000000f, 0.000000f, 0.000000f}},
    {-2, -1, -1, 0.000000f, {0.425932f, 0.368589f, 0.205479f}},
    {-2, -1, -1, 0.000000f, {0.236317f, 0.365754f, 0.397929f}},
    {-2, -1, -1, 0.000000f, {0.613419f, 0.235052f, 0.151529f}},
    {216, 15, 24, -0.438123f, {0.000000f, 0.000000f, 0.000000f}},
    {195, 16, 23, 0.108843f, {0.000000f, 0.000000f, 0.000000f}},
    {179, 17, 18, -0.352683f, {0.000000f, 0.000000f, 0.000000f}},
    {-2, -1, -1, 0.000000f, {0.456947f, 0.176125f, 0.366928f}},
    {260, 19, 22, -1.488317f, {0.000000f, 0.000000f, 0.000000f}},
    {196, 20, 21, -0.226955f, {0.000000f, 0.000000f, 0.000000f}},
    {-2, -1, -1, 0.000000f, {0.146444f, 0.744770f, 0.108787f}},
    {-2, -1, -1, 0.000000f, {0.145695f, 0.026490f, 0.827815f}},
    {-2, -1, -1, 0.000000f, {0.118852f, 0.087432f, 0.793716f}},
    {-2, -1, -1, 0.000000f, {0.138776f, 0.706122f, 0.155102f}},
    {190, 25, 44, -0.023532f, {0.000000f, 0.000000f, 0.000000f}},
    {194, 26, 43, 0.170494f, {0.000000f, 0.000000f, 0.000000f}},
    {279, 27, 28, -1.469207f, {0.000000f, 0.000000f, 0.000000f}},
    {-2, -1, -1, 0.000000f, {0.568182f, 0.160511f, 0.271307f}},
    {66, 29, 42, 0.210833f, {0.000000f, 0.000000f, 0.000000f}},
    {31, 30, 41, 0.598523f, {0.000000f, 0.000000f, 0.000000f}},
    {64, 31, 40, -0.222798f, {0.000000f, 0.000000f, 0.000000f}},
    {180, 32, 39, 0.309880f, {0.000000f, 0.000000f, 0.000000f}},
    {27, 33, 34, -1.345484f, {0.000000f, 0.000000f, 0.000000f}},
    {-2, -1, -1, 0.000000f, {0.384232f, 0.323651f, 0.292116f}},
    {135, 35, 36, -0.882573f, {0.000000f, 0.000000f, 0.000000f}},
    {-2, -1, -1, 0.000000f, {0.204148f, 0.064410f, 0.731441f}},
    {177, 37, 38, -0.281151f, {0.000000f, 0.000000f, 0.000000f}},
    {-2, -1, -1, 0.000000f, {0.242647f, 0.441176f, 0.316176f}},
    {-2, -1, -1, 0.000000f, {0.127404f, 0.079327f, 0.793269f}},
    {-2, -1, -1, 0.000000f, {0.006173f, 0.956790f, 0.037037f}},
    {-2, -1, -1, 0.000000f, {0.355959f, 0.324679f, 0.319362f}},
    {-2, -1, -1, 0.000000f, {0.252688f, 0.553763f, 0.193548f}},
    {-2, -1, -1, 0.000000f, {0.292045f, 0.191669f, 0.516286f}},
    {-2, -1, -1, 0.000000f, {0.185990f, 0.770531f, 0.043478f}},
    {9, 45, 56, 0.875761f, {0.000000f, 0.000000f, 0.000000f}},
    {168, 46, 47, -0.198351f, {0.000000f, 0.000000f, 0.000000f}},
    {-2, -1, -1, 0.000000f, {0.015639f, 0.906164f, 0.078197f}},
    {237, 48, 53, 0.809300f, {0.000000f, 0.000000f, 0.000000f}},
    {266, 49, 52, 0.671480f, {0.000000f, 0.000000f, 0.000000f}},
    {31, 50, 51, 0.680373f, {0.000000f, 0.000000f, 0.000000f}},
    {-2, -1, -1, 0.000000f, {0.353108f, 0.258970f, 0.387922f}},
    {-2, -1, -1, 0.000000f, {0.216518f, 0.613839f, 0.169643f}},
    {-2, -1, -1, 0.000000f, {0.277668f, 0.172431f, 0.549901f}},
    {164, 54, 55, 0.633685f, {0.000000f, 0.000000f, 0.000000f}},
    {-2, -1, -1, 0.000000f, {0.085884f, 0.838105f, 0.076012f}},
    {-2, -1, -1, 0.000000f, {0.275255f, 0.353427f, 0.371318f}},
    {78, 57, 58, 1.678564f, {0.000000f, 0.000000f, 0.000000f}},
    {-2, -1, -1, 0.000000f, {0.147181f, 0.777778f, 0.075041f}},
    {-2, -1, -1, 0.000000f, {0.252011f, 0.388740f, 0.359249f}},
};

const TreeNode *const TREES[TREE_N_TREES] = {tree0_nodes};

inline void treePredictSingle(const TreeNode *nodes, const float *x,
                              float *outProbs) {
  int node = 0;
  while (nodes[node].feature != -2) {
    if (x[nodes[node].feature] <= nodes[node].threshold)
      node = nodes[node].left;
    else
      node = nodes[node].right;
  }
  for (int c = 0; c < TREE_N_CLASSES; c++)
    outProbs[c] = nodes[node].probs[c];
}

// WARNING: x must be an array of TREE_N_FEATURES extracted statistical features
// Order: [all means, all mins, all maxs, all stds, all rms]
inline void treeForestPredict(const float *x, float *outProbs) {
  float leaf[TREE_N_CLASSES];
  for (int c = 0; c < TREE_N_CLASSES; c++)
    outProbs[c] = 0.0f;
  for (int t = 0; t < TREE_N_TREES; t++) {
    treePredictSingle(TREES[t], x, leaf);
    for (int c = 0; c < TREE_N_CLASSES; c++)
      outProbs[c] += leaf[c];
  }
  for (int c = 0; c < TREE_N_CLASSES; c++)
    outProbs[c] /= TREE_N_TREES;
}

// CNN + Tree ensemble: weighted average of the two probability vectors.
inline void ensembleBlend(const float *cnnProbs, const float *treeProbs,
                          float alpha, float *outProbs) {
  for (int c = 0; c < TREE_N_CLASSES; c++)
    outProbs[c] = alpha * cnnProbs[c] + (1.0f - alpha) * treeProbs[c];
}

inline int argmaxProbs(const float *probs, int n) {
  int best = 0;
  for (int i = 1; i < n; i++)
    if (probs[i] > probs[best])
      best = i;
  return best;
}

#endif
