name: Code Quality (Linting)

on: [push, pull_request]

jobs:
  style-and-logic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # -------------------------
      # Clang Format
      # -------------------------
      - name: Install Clang-Format
        run: sudo apt-get update && sudo apt-get install -y clang-format

      - name: Check Formatting
        run: |
          find src include test -type f \( -name "*.h" -o -name "*.hpp" -o -name "*.c" -o -name "*.cc" -o -name "*.cpp" \) \
            -print0 | xargs -0 clang-format --dry-run --Werror

      # -------------------------
      # Install Arduino CLI
      # -------------------------
      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          sudo mv bin/arduino-cli /usr/local/bin/

      - name: Update Arduino Index
        run: arduino-cli core update-index

      # -------------------------
      # Install Nano 33 BLE core
      # -------------------------
      - name: Install Arduino Mbed Nano core
        run: arduino-cli core install arduino:mbed_nano

      # -------------------------
      # Compile Sketch
      # -------------------------
      - name: Compile Arduino Sketch
        run: |
          arduino-cli compile \
            --fqbn arduino:mbed_nano:nano33ble \
            ./Fagprojekt
